// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAztaPugQJ3GFsVsj9n-5Kra9r4YdOjxZU',
    appId: '1:241211711120:web:8ac2dff56edf2cf6f60215',
    messagingSenderId: '241211711120',
    projectId: 'mr-sunshine-54e48',
    authDomain: 'mr-sunshine-54e48.firebaseapp.com',
    storageBucket: 'mr-sunshine-54e48.appspot.com',
    measurementId: 'G-KB77SFZMNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlE8zRjT9YqVoWB59CPsUUEkW1GyrG00',
    appId: '1:241211711120:android:70a43a59de1a24c6f60215',
    messagingSenderId: '241211711120',
    projectId: 'mr-sunshine-54e48',
    storageBucket: 'mr-sunshine-54e48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23mV9vZbr-OFW3tgf1UOP01iXQRq8DYs',
    appId: '1:241211711120:ios:86a55783b4765711f60215',
    messagingSenderId: '241211711120',
    projectId: 'mr-sunshine-54e48',
    storageBucket: 'mr-sunshine-54e48.appspot.com',
    androidClientId: '241211711120-u6hjdtslob7tdca9u57b1g2p8uu6g6t8.apps.googleusercontent.com',
    iosClientId: '241211711120-vbkns5mju8qohonhullt44gi7r83h3mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrSunshineClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23mV9vZbr-OFW3tgf1UOP01iXQRq8DYs',
    appId: '1:241211711120:ios:beea10648f77a05df60215',
    messagingSenderId: '241211711120',
    projectId: 'mr-sunshine-54e48',
    storageBucket: 'mr-sunshine-54e48.appspot.com',
    androidClientId: '241211711120-u6hjdtslob7tdca9u57b1g2p8uu6g6t8.apps.googleusercontent.com',
    iosClientId: '241211711120-9u9upvlddnq4pr1k1vp827ehs8ibe34c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrSunshineClient.RunnerTests',
  );
}
